// <auto-generated />
using System;
using ClothingStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClothingStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726114415_intitialcreate")]
    partial class intitialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClothingStore.Models.Category", b =>
                {
                    b.Property<int>("intSeqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("intSeqId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("dtCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("varDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("varName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("intSeqId");

                    b.ToTable("tblCategories");
                });

            modelBuilder.Entity("ClothingStore.Models.Product", b =>
                {
                    b.Property<int>("intSeqId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("intSeqId"));

                    b.Property<DateTime?>("dtCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dtUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("flDiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("flPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("intCategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("intQuantity")
                        .HasColumnType("int");

                    b.Property<bool?>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("isFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("varBrand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("varColor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("varDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("varImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("varName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("varProductCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("varSize")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("intSeqId");

                    b.HasIndex("intCategoryId");

                    b.ToTable("tblProducts");
                });

            modelBuilder.Entity("ClothingStore.Models.Product", b =>
                {
                    b.HasOne("ClothingStore.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("intCategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
